on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-request:
    name: Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Graal
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check
        run: ./gradlew check